# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Wed Jun  5 00:19:43 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 230)
        Form.setMaximumSize(QtCore.QSize(400, 265))
        self.formLayoutWidget = QtGui.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 361, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.price = QtGui.QSpinBox(self.formLayoutWidget)
        self.price.setMinimumSize(QtCore.QSize(200, 25))
        self.price.setMaximumSize(QtCore.QSize(200, 25))
        self.price.setMaximum(2147483647)
        self.price.setObjectName("price")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.price)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.brand = QtGui.QComboBox(self.formLayoutWidget)
        self.brand.setMinimumSize(QtCore.QSize(200, 25))
        self.brand.setMaximumSize(QtCore.QSize(200, 25))
        self.brand.setObjectName("brand")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.brand)
        self.name = QtGui.QLineEdit(self.formLayoutWidget)
        self.name.setMinimumSize(QtCore.QSize(200, 25))
        self.name.setMaximumSize(QtCore.QSize(200, 25))
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.name)
        self.desc = QtGui.QLineEdit(self.formLayoutWidget)
        self.desc.setMinimumSize(QtCore.QSize(200, 25))
        self.desc.setMaximumSize(QtCore.QSize(200, 25))
        self.desc.setObjectName("desc")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.desc)
        self.color = QtGui.QLineEdit(self.formLayoutWidget)
        self.color.setMinimumSize(QtCore.QSize(200, 25))
        self.color.setMaximumSize(QtCore.QSize(200, 25))
        self.color.setObjectName("color")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.color)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 190, 191, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_cancel = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.message = QtGui.QLabel(Form)
        self.message.setGeometry(QtCore.QRect(20, 230, 361, 20))
        self.message.setText("")
        self.message.setTextFormat(QtCore.Qt.AutoText)
        self.message.setScaledContents(False)
        self.message.setAlignment(QtCore.Qt.AlignCenter)
        self.message.setObjectName("message")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Agregar producto", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Descripción:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Precio:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Marca Asociada:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setText(QtGui.QApplication.translate("Form", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Form", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))

